# Generated by Django 2.2.7 on 2020-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20191105_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.EmailField(default='email@web.com', help_text='Email', max_length=600),
        ),
    ]
